<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\EventsManagements.InMemoryBroker\EventsManagements.InMemoryBroker.csproj" />
      <ProjectReference Include="..\EventsManagement.Notifications.Entities\EventsManagement.Notifications.Entities.csproj" />
      <ProjectReference Include="..\EventsManagement.Notifications.Infrastructure\EventsManagement.Notifications.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Azure.Messaging.EventHubs" Version="5.12.2" />
      <PackageReference Include="Azure.Messaging.EventHubs.Processor" Version="5.12.2" />
    </ItemGroup>

</Project>
